workflows:
  ios-app:
    name: iOS App Build
    environment:
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - "youremail@example.com"
